### ISSUE TITLE
gnu_printf attribute makes it fail with clang

### ISSUE THREAD

**Issue by vincentbernat** [libcheck/check#276]
Hey!

When compiling with clang, I am getting an error around `gnu_printf` attribute introduced in #249.

```
$ clang --version

Apple LLVM version 9.1.0 (clang-902.0.39.2)

Target: x86_64-apple-darwin17.7.0
```

```
In file included from check_marshal.c:20:

/usr/local/Cellar/check/0.15.0/include/check.h:504:72: fatal error: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]

                                            ...) CK_ATTRIBUTE_NORETURN CK_ATTRIBUTE_FORMAT(gnu_printf, 3, 4);

                                                                       ^

/usr/local/Cellar/check/0.15.0/include/check.h:67:54: note: expanded from macro 'CK_ATTRIBUTE_FORMAT'

#define CK_ATTRIBUTE_FORMAT(a, b, c) __attribute__ ((format (a, b, c)))

                                                     ^

1 error generated.
```

**Comment by brarcher** [comment]
Thanks for reporting this. It should now be resolved in https://github.com/libcheck/check/pull/282. Also, I've added a PR test which explicitly uses clang in https://github.com/libcheck/check/pull/279.
